image: node:20

stages:
  - install
  - test
  - build

install:
  stage: install
  script:
    - npm install

test:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build